In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler

In [2]:
def get_data_dir():
    return '../data/'


def merged_file_path():
    return get_data_dir()+'Merged_Data_Excel.xlsx'


def train_file_path():
    return get_data_dir()+'train_data.pkl'


In [3]:
df = pd.read_excel(merged_file_path(),index_col=0,parse_dates=True )

In [4]:
df.head(5)

Open      High       Low     Close   Volume  \
Date                                                          
1995-01-01  13.09375  13.12500  12.87500  12.87500  3295200   
1995-01-02  13.09375  13.12500  12.87500  12.87500  3295200   
1995-01-03  12.87500  12.96875  12.81250  12.93750  5140400   
1995-01-04  12.93750  12.93750  12.59375  12.65625  6486000   
1995-01-05  12.65625  12.68750  12.46875  12.59375  8465600   

            SPOT_per_troy_ounce  days_since_epoch  
Date                                               
1995-01-01               383.25              9131  
1995-01-02               383.25              9132  
1995-01-03               380.90              9133  
1995-01-04               375.60              9134  
1995-01-05               375.30              9135

In [5]:
scaler = MinMaxScaler()
scaled = scaler.fit_transform(df)

In [6]:
scaled.shape

(8766, 7)

In [45]:
scaled[8763]

array([0.9239726 , 0.92642657, 0.91540227, 0.91341602, 0.09940339,
       0.62489344, 0.99977182])

In [8]:
timesteps=600

In [9]:
scaled[2:4]

array([[0.01540657, 0.01543611, 0.01642036, 0.0171664 , 0.03383524,
        0.07800512, 0.00022818],
       [0.01702832, 0.01462368, 0.01067323, 0.00980937, 0.04475758,
        0.07477774, 0.00034227]])

In [16]:
rowcount = scaled.shape[0]
close_price_col_idx=3

In [33]:
X_list=[]
Y_list=[]

In [34]:
for i in range(rowcount,timesteps+1,-1):
    start_row=i-(timesteps)
    end_row=i-2
    y_val=scaled[i-1][close_price_col_idx]
    Y_list.append(y_val)
    x=scaled[start_row:end_row]
    X_list.append(x)

In [35]:
len(Y_list)

8165

In [36]:
len(X_list)

8165

In [44]:
X_list[0][597]

array([0.9239726 , 0.92642657, 0.91540227, 0.91341602, 0.09940339,
       0.62489344, 0.99977182])

In [47]:
batch_size=32

In [48]:
X_arr=np.asarray(X_list)

In [49]:
X_arr.shape

(8165, 598, 7)